language: python
matrix:
  include:
    - python: 3.6
      dist: bionic
    - python: 3.7
      dist: bionic
      sudo: true
    - python: 3.8
      dist: bionic
      sudo: true
install:
  - pip install -r tests_requirements.txt
  - pip install coveralls
  - gem install mdl
script:
  - coverage run -m unittest discover
  - flake8 canvasapi tests
  - mdl . .github
  - ./scripts/run_black.sh
  - python scripts/alphabetic.py
after_success:
  - coveralls
notifications:
  slack:
    secure: oLrAMXKVN9EKOyvROg5ZZUQgeleKq6lsVslm/Jtg516LtdBnLiAA672xMrwB0m8UtSJvoz4m1BrBQBeO+OzxlmioJHDvm//MMXv8wpfBdi18ojBA/5wjYfYP4eta/9j1x4myWH9ygcJOdKhALOSt4fwKsmIRDt6YTensOaqcCTiS2YjtAWMLrKvlathpdMokx0k7FVluJJ+zEfzNote75AP7yq6nFFe9j0ALX7YuNFytshZXi82aKZpAuUGMNLjcL+B5acLKSYqF214sTVETPa2mrhja+89+W9512X3ecRdHPC6Ud10ICD6ap0XMrOcgNW8XREV0pDIDPrMJgSUFiFWMhvrkMjfnmJB2nrINPTc3CrMmmk8Hk1XYta+iA4yAEUb9dhkKmkxMZWtn7TZ7DiKaAXznwj6poGrnN+NXeWfoJ0j2pAUrcO4Jn9e43+ORMDYqCFV3QemtykbX0HKgVfOTx5F1ZBGULiMi7U3q5naieGep5j+OxNI9bcQMUoM6O+VxmkjtB1/8/F7PlKHrA/7Z1+s+1HM00lSvw5qAhkInPgkLU+X495+TsEfqJuVZIUIAS1jDDSuo3bTHHUYzDwE9UF/dYN/nVDiUEVa4xYe+UrAFuPnezL/bdezVwzoGd1Mb5HKJxs90wxYIZFkReivA1z4bQsYh+A/QbYKewR0=
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: kO9KrFtczXgO/u88YpNJDqincHYHKoj8sljkCheLuVLjGnYzhakUbovCL7zzmhnx8JIicpD7j+oa1rbFidNQa8GJ32dwHnNl22126OL6IdfNyLisRPlWlGCyJ3X/h8KGRWhglESBweKDWpVj1QTVJpfn5xWv953tKovcxmudO8lTIDZyIzFLRdVcnOsmSTwkslTmILBufs8p195fso4xOmwGirWBefbgmSUZ6Oxbg3kEu3NXUuh9n+egwhFCTS9m6sl5e9H+a+Oq8nhfbpI0BB/CpBBhpkqMsewmK+CVPNtbj3f3bUnnZC2czCc74QeH2cQr/iCR9Y0JbyM8WY+/0lBTeG5I/4k+ZPgiSiv8g23QvPLcMe297DTBldONEFBKgDFcIzAA3tQ8JXjLXLp+NXosFhMKZcFLXg43TGx1X2nVgcPPvTsxgJXAKOK2VydF8ZAS0v/9nowEZ1yS1qDNpFJhBWyKdTzDXeZ2xruK9OOUHKDFdF/jPqnVkPSRRQjT4uIVCLEab7RzzqhZaZRIf/2gTHfErjVlb2cv5JxlsUt1RJB8JmbkYkd01K48RR8ZJ72ARh3P4x2iYfXXkgXOLJYiY3CW5Uqw/dAqpvJv8mt49UIa9J2nVsxEzOvrqpYFVZf3e/BTBm7p8mCT4MKxCSiglzV6LgS+ZMS7uvCViY4=
  on:
    tags: true
    skip_existing: true
